#!/bin/bash
if [ "$#" == 0 ]
then
  docker run --env-file=/vagrant/.env --name=web --volume=/vagrant:/project --link=elasticsearch:elasticsearch --tty=false --interactive=false --detach=true web
else
  docker run --env-file=/vagrant/.env --name=web_run --volume=/vagrant:/project --link=elasticsearch:elasticsearch --tty=true --interactive=true --detach=false --rm=true web $@
fi
